name: Check GitHub Actions Workflows

on:
  push:
    branches:
      - main
      - 'renovate/**'
    paths: &paths
      - '.github/workflows/*.ya?ml'

  pull_request:
    branches:
      - main
    paths: *paths

  workflow_call:
  workflow_dispatch:

jobs:
  _:
    uses: jonasgeiler/.github/.github/workflows/check-github-actions-workflows.yaml@b6023c67ebb75d9d4ae68f33a919f2a3a1eb7ce9 # main
