name: Check GitHub Actions Workflows

on:
  push:
    branches:
      - main
      - 'renovate/**'
    paths: &paths
      - '.github/workflows/*.ya?ml'

  pull_request:
    branches:
      - main
    paths: *paths

  workflow_call:
  workflow_dispatch:

jobs:
  _:
    uses: jonasgeiler/.github/.github/workflows/check-github-actions-workflows.yaml@baa08fee9308a6d466df0324471d01feb5412b61 # main
