name: Check

on:
  push:
    branches:
      - main
      - 'renovate/**'
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'assets/**'
      - '.github/**'
      - '!.github/workflows/check.yml'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'assets/**'
      - '.github/**'
      - '!.github/workflows/check.yml'

  workflow_dispatch:
  workflow_call:

jobs:
  lint-check-and-test:
    name: Lint, Check & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 18
          cache: pnpm

      - name: Install Dependencies
        run: |
          pnpm install
          pnpm exec playwright install --with-deps

      - name: Lint
        run: pnpm run lint

      - name: Check
        run: pnpm run check

      - name: Test
        run: pnpm run test
