name: Check Shell Scripts

on:
  push:
    branches:
      - main
      - 'renovate/**'
    paths: &paths
      - '**.ash'
      - '**.bash'
      - '**.bats'
      - '**.dash'
      - '**.ksh'
      - '**.sh'
      - '.githooks/*'

      - .github/workflows/check-shell-scripts.ya?ml

  pull_request:
    branches:
      - main
    paths: *paths

  workflow_call:
  workflow_dispatch:

jobs:
  _:
    uses: jonasgeiler/.github/.github/workflows/check-shell-scripts.yaml@b6023c67ebb75d9d4ae68f33a919f2a3a1eb7ce9 # main
